#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketBarkod.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BarcodeSystem")]
	public partial class BarkodDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStock(Stock instance);
    partial void UpdateStock(Stock instance);
    partial void DeleteStock(Stock instance);
    partial void InsertSale(Sale instance);
    partial void UpdateSale(Sale instance);
    partial void DeleteSale(Sale instance);
    partial void InsertRefCustomer(RefCustomer instance);
    partial void UpdateRefCustomer(RefCustomer instance);
    partial void DeleteRefCustomer(RefCustomer instance);
    partial void InsertProccesList(ProccesList instance);
    partial void UpdateProccesList(ProccesList instance);
    partial void DeleteProccesList(ProccesList instance);
    partial void InsertPaymentMethod(PaymentMethod instance);
    partial void UpdatePaymentMethod(PaymentMethod instance);
    partial void DeletePaymentMethod(PaymentMethod instance);
    partial void InsertOperationProduct(OperationProduct instance);
    partial void UpdateOperationProduct(OperationProduct instance);
    partial void DeleteOperationProduct(OperationProduct instance);
    partial void InsertCustomers(Customers instance);
    partial void UpdateCustomers(Customers instance);
    partial void DeleteCustomers(Customers instance);
    partial void InsertCustomerProcces(CustomerProcces instance);
    partial void UpdateCustomerProcces(CustomerProcces instance);
    partial void DeleteCustomerProcces(CustomerProcces instance);
    partial void InsertCategories(Categories instance);
    partial void UpdateCategories(Categories instance);
    partial void DeleteCategories(Categories instance);
    partial void InsertProducts(Products instance);
    partial void UpdateProducts(Products instance);
    partial void DeleteProducts(Products instance);
    #endregion
		
		public BarkodDataDataContext() : 
				base(global::MarketBarkod.Properties.Settings.Default.Local, mappingSource)
		{
			OnCreated();
		}
		
		public BarkodDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BarkodDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BarkodDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BarkodDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Stock> Stock
		{
			get
			{
				return this.GetTable<Stock>();
			}
		}
		
		public System.Data.Linq.Table<Sale> Sale
		{
			get
			{
				return this.GetTable<Sale>();
			}
		}
		
		public System.Data.Linq.Table<RefCustomer> RefCustomer
		{
			get
			{
				return this.GetTable<RefCustomer>();
			}
		}
		
		public System.Data.Linq.Table<ProccesList> ProccesList
		{
			get
			{
				return this.GetTable<ProccesList>();
			}
		}
		
		public System.Data.Linq.Table<PaymentMethod> PaymentMethod
		{
			get
			{
				return this.GetTable<PaymentMethod>();
			}
		}
		
		public System.Data.Linq.Table<OperationProduct> OperationProduct
		{
			get
			{
				return this.GetTable<OperationProduct>();
			}
		}
		
		public System.Data.Linq.Table<Customers> Customers
		{
			get
			{
				return this.GetTable<Customers>();
			}
		}
		
		public System.Data.Linq.Table<CustomerProcces> CustomerProcces
		{
			get
			{
				return this.GetTable<CustomerProcces>();
			}
		}
		
		public System.Data.Linq.Table<Categories> Categories
		{
			get
			{
				return this.GetTable<Categories>();
			}
		}
		
		public System.Data.Linq.Table<Products> Products
		{
			get
			{
				return this.GetTable<Products>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stock")]
	public partial class Stock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StockID;
		
		private int _ProductID;
		
		private int _Piece;
		
		private System.Nullable<System.DateTime> _StockEntryDate;
		
		private string _ProductManufacturer;
		
		private System.Nullable<decimal> _PurchasePrice;
		
		private EntityRef<Products> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStockIDChanging(int value);
    partial void OnStockIDChanged();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnPieceChanging(int value);
    partial void OnPieceChanged();
    partial void OnStockEntryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStockEntryDateChanged();
    partial void OnProductManufacturerChanging(string value);
    partial void OnProductManufacturerChanged();
    partial void OnPurchasePriceChanging(System.Nullable<decimal> value);
    partial void OnPurchasePriceChanged();
    #endregion
		
		public Stock()
		{
			this._Products = default(EntityRef<Products>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StockID
		{
			get
			{
				return this._StockID;
			}
			set
			{
				if ((this._StockID != value))
				{
					this.OnStockIDChanging(value);
					this.SendPropertyChanging();
					this._StockID = value;
					this.SendPropertyChanged("StockID");
					this.OnStockIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					if (this._Products.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piece", DbType="Int NOT NULL")]
		public int Piece
		{
			get
			{
				return this._Piece;
			}
			set
			{
				if ((this._Piece != value))
				{
					this.OnPieceChanging(value);
					this.SendPropertyChanging();
					this._Piece = value;
					this.SendPropertyChanged("Piece");
					this.OnPieceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockEntryDate", DbType="Date")]
		public System.Nullable<System.DateTime> StockEntryDate
		{
			get
			{
				return this._StockEntryDate;
			}
			set
			{
				if ((this._StockEntryDate != value))
				{
					this.OnStockEntryDateChanging(value);
					this.SendPropertyChanging();
					this._StockEntryDate = value;
					this.SendPropertyChanged("StockEntryDate");
					this.OnStockEntryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductManufacturer", DbType="NVarChar(150)")]
		public string ProductManufacturer
		{
			get
			{
				return this._ProductManufacturer;
			}
			set
			{
				if ((this._ProductManufacturer != value))
				{
					this.OnProductManufacturerChanging(value);
					this.SendPropertyChanging();
					this._ProductManufacturer = value;
					this.SendPropertyChanged("ProductManufacturer");
					this.OnProductManufacturerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchasePrice", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PurchasePrice
		{
			get
			{
				return this._PurchasePrice;
			}
			set
			{
				if ((this._PurchasePrice != value))
				{
					this.OnPurchasePriceChanging(value);
					this.SendPropertyChanging();
					this._PurchasePrice = value;
					this.SendPropertyChanged("PurchasePrice");
					this.OnPurchasePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Products_Stock", Storage="_Products", ThisKey="ProductID", OtherKey="ProductID", IsForeignKey=true)]
		public Products Products
		{
			get
			{
				return this._Products.Entity;
			}
			set
			{
				Products previousValue = this._Products.Entity;
				if (((previousValue != value) 
							|| (this._Products.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Products.Entity = null;
						previousValue.Stock.Remove(this);
					}
					this._Products.Entity = value;
					if ((value != null))
					{
						value.Stock.Add(this);
						this._ProductID = value.ProductID;
					}
					else
					{
						this._ProductID = default(int);
					}
					this.SendPropertyChanged("Products");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sale")]
	public partial class Sale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SaleID;
		
		private System.Nullable<System.DateTime> _SaleDate;
		
		private System.Nullable<decimal> _TotalPrice;
		
		private System.Nullable<int> _CustomerID;
		
		private System.Nullable<decimal> _TotalDiscount;
		
		private int _PaymentMethodSale;
		
		private EntitySet<OperationProduct> _OperationProduct;
		
		private EntityRef<PaymentMethod> _PaymentMethod;
		
		private EntityRef<Customers> _Customers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSaleIDChanging(int value);
    partial void OnSaleIDChanged();
    partial void OnSaleDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaleDateChanged();
    partial void OnTotalPriceChanging(System.Nullable<decimal> value);
    partial void OnTotalPriceChanged();
    partial void OnCustomerIDChanging(System.Nullable<int> value);
    partial void OnCustomerIDChanged();
    partial void OnTotalDiscountChanging(System.Nullable<decimal> value);
    partial void OnTotalDiscountChanged();
    partial void OnPaymentMethodSaleChanging(int value);
    partial void OnPaymentMethodSaleChanged();
    #endregion
		
		public Sale()
		{
			this._OperationProduct = new EntitySet<OperationProduct>(new Action<OperationProduct>(this.attach_OperationProduct), new Action<OperationProduct>(this.detach_OperationProduct));
			this._PaymentMethod = default(EntityRef<PaymentMethod>);
			this._Customers = default(EntityRef<Customers>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SaleID
		{
			get
			{
				return this._SaleID;
			}
			set
			{
				if ((this._SaleID != value))
				{
					this.OnSaleIDChanging(value);
					this.SendPropertyChanging();
					this._SaleID = value;
					this.SendPropertyChanged("SaleID");
					this.OnSaleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> SaleDate
		{
			get
			{
				return this._SaleDate;
			}
			set
			{
				if ((this._SaleDate != value))
				{
					this.OnSaleDateChanging(value);
					this.SendPropertyChanging();
					this._SaleDate = value;
					this.SendPropertyChanged("SaleDate");
					this.OnSaleDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPrice", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TotalPrice
		{
			get
			{
				return this._TotalPrice;
			}
			set
			{
				if ((this._TotalPrice != value))
				{
					this.OnTotalPriceChanging(value);
					this.SendPropertyChanging();
					this._TotalPrice = value;
					this.SendPropertyChanged("TotalPrice");
					this.OnTotalPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int")]
		public System.Nullable<int> CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					if (this._Customers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDiscount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TotalDiscount
		{
			get
			{
				return this._TotalDiscount;
			}
			set
			{
				if ((this._TotalDiscount != value))
				{
					this.OnTotalDiscountChanging(value);
					this.SendPropertyChanging();
					this._TotalDiscount = value;
					this.SendPropertyChanged("TotalDiscount");
					this.OnTotalDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentMethodSale", DbType="Int NOT NULL")]
		public int PaymentMethodSale
		{
			get
			{
				return this._PaymentMethodSale;
			}
			set
			{
				if ((this._PaymentMethodSale != value))
				{
					if (this._PaymentMethod.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPaymentMethodSaleChanging(value);
					this.SendPropertyChanging();
					this._PaymentMethodSale = value;
					this.SendPropertyChanged("PaymentMethodSale");
					this.OnPaymentMethodSaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sale_OperationProduct", Storage="_OperationProduct", ThisKey="SaleID", OtherKey="SaleProduct")]
		public EntitySet<OperationProduct> OperationProduct
		{
			get
			{
				return this._OperationProduct;
			}
			set
			{
				this._OperationProduct.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PaymentMethod_Sale", Storage="_PaymentMethod", ThisKey="PaymentMethodSale", OtherKey="PaymentMethodID", IsForeignKey=true)]
		public PaymentMethod PaymentMethod
		{
			get
			{
				return this._PaymentMethod.Entity;
			}
			set
			{
				PaymentMethod previousValue = this._PaymentMethod.Entity;
				if (((previousValue != value) 
							|| (this._PaymentMethod.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PaymentMethod.Entity = null;
						previousValue.Sale.Remove(this);
					}
					this._PaymentMethod.Entity = value;
					if ((value != null))
					{
						value.Sale.Add(this);
						this._PaymentMethodSale = value.PaymentMethodID;
					}
					else
					{
						this._PaymentMethodSale = default(int);
					}
					this.SendPropertyChanged("PaymentMethod");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customers_Sale", Storage="_Customers", ThisKey="CustomerID", OtherKey="CustomerID", IsForeignKey=true)]
		public Customers Customers
		{
			get
			{
				return this._Customers.Entity;
			}
			set
			{
				Customers previousValue = this._Customers.Entity;
				if (((previousValue != value) 
							|| (this._Customers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customers.Entity = null;
						previousValue.Sale.Remove(this);
					}
					this._Customers.Entity = value;
					if ((value != null))
					{
						value.Sale.Add(this);
						this._CustomerID = value.CustomerID;
					}
					else
					{
						this._CustomerID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Customers");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OperationProduct(OperationProduct entity)
		{
			this.SendPropertyChanging();
			entity.Sale = this;
		}
		
		private void detach_OperationProduct(OperationProduct entity)
		{
			this.SendPropertyChanging();
			entity.Sale = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RefCustomer")]
	public partial class RefCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RefCustomerID;
		
		private string _RefCustomerName;
		
		private string _RefCustomerSurname;
		
		private System.Nullable<bool> _isActive;
		
		private EntitySet<Customers> _Customers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRefCustomerIDChanging(int value);
    partial void OnRefCustomerIDChanged();
    partial void OnRefCustomerNameChanging(string value);
    partial void OnRefCustomerNameChanged();
    partial void OnRefCustomerSurnameChanging(string value);
    partial void OnRefCustomerSurnameChanged();
    partial void OnisActiveChanging(System.Nullable<bool> value);
    partial void OnisActiveChanged();
    #endregion
		
		public RefCustomer()
		{
			this._Customers = new EntitySet<Customers>(new Action<Customers>(this.attach_Customers), new Action<Customers>(this.detach_Customers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefCustomerID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RefCustomerID
		{
			get
			{
				return this._RefCustomerID;
			}
			set
			{
				if ((this._RefCustomerID != value))
				{
					this.OnRefCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._RefCustomerID = value;
					this.SendPropertyChanged("RefCustomerID");
					this.OnRefCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefCustomerName", DbType="NVarChar(150)")]
		public string RefCustomerName
		{
			get
			{
				return this._RefCustomerName;
			}
			set
			{
				if ((this._RefCustomerName != value))
				{
					this.OnRefCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._RefCustomerName = value;
					this.SendPropertyChanged("RefCustomerName");
					this.OnRefCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefCustomerSurname", DbType="NVarChar(150)")]
		public string RefCustomerSurname
		{
			get
			{
				return this._RefCustomerSurname;
			}
			set
			{
				if ((this._RefCustomerSurname != value))
				{
					this.OnRefCustomerSurnameChanging(value);
					this.SendPropertyChanging();
					this._RefCustomerSurname = value;
					this.SendPropertyChanged("RefCustomerSurname");
					this.OnRefCustomerSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit")]
		public System.Nullable<bool> isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RefCustomer_Customers", Storage="_Customers", ThisKey="RefCustomerID", OtherKey="CustomerReference")]
		public EntitySet<Customers> Customers
		{
			get
			{
				return this._Customers;
			}
			set
			{
				this._Customers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Customers(Customers entity)
		{
			this.SendPropertyChanging();
			entity.RefCustomer = this;
		}
		
		private void detach_Customers(Customers entity)
		{
			this.SendPropertyChanging();
			entity.RefCustomer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProccesList")]
	public partial class ProccesList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProccesID;
		
		private string _ProccesType;
		
		private EntitySet<CustomerProcces> _CustomerProcces;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProccesIDChanging(int value);
    partial void OnProccesIDChanged();
    partial void OnProccesTypeChanging(string value);
    partial void OnProccesTypeChanged();
    #endregion
		
		public ProccesList()
		{
			this._CustomerProcces = new EntitySet<CustomerProcces>(new Action<CustomerProcces>(this.attach_CustomerProcces), new Action<CustomerProcces>(this.detach_CustomerProcces));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProccesID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProccesID
		{
			get
			{
				return this._ProccesID;
			}
			set
			{
				if ((this._ProccesID != value))
				{
					this.OnProccesIDChanging(value);
					this.SendPropertyChanging();
					this._ProccesID = value;
					this.SendPropertyChanged("ProccesID");
					this.OnProccesIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProccesType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ProccesType
		{
			get
			{
				return this._ProccesType;
			}
			set
			{
				if ((this._ProccesType != value))
				{
					this.OnProccesTypeChanging(value);
					this.SendPropertyChanging();
					this._ProccesType = value;
					this.SendPropertyChanged("ProccesType");
					this.OnProccesTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProccesList_CustomerProcces", Storage="_CustomerProcces", ThisKey="ProccesID", OtherKey="ProccesType")]
		public EntitySet<CustomerProcces> CustomerProcces
		{
			get
			{
				return this._CustomerProcces;
			}
			set
			{
				this._CustomerProcces.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CustomerProcces(CustomerProcces entity)
		{
			this.SendPropertyChanging();
			entity.ProccesList = this;
		}
		
		private void detach_CustomerProcces(CustomerProcces entity)
		{
			this.SendPropertyChanging();
			entity.ProccesList = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PaymentMethod")]
	public partial class PaymentMethod : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PaymentMethodID;
		
		private string _PaymentMethodName;
		
		private EntitySet<Sale> _Sale;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPaymentMethodIDChanging(int value);
    partial void OnPaymentMethodIDChanged();
    partial void OnPaymentMethodNameChanging(string value);
    partial void OnPaymentMethodNameChanged();
    #endregion
		
		public PaymentMethod()
		{
			this._Sale = new EntitySet<Sale>(new Action<Sale>(this.attach_Sale), new Action<Sale>(this.detach_Sale));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentMethodID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PaymentMethodID
		{
			get
			{
				return this._PaymentMethodID;
			}
			set
			{
				if ((this._PaymentMethodID != value))
				{
					this.OnPaymentMethodIDChanging(value);
					this.SendPropertyChanging();
					this._PaymentMethodID = value;
					this.SendPropertyChanged("PaymentMethodID");
					this.OnPaymentMethodIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentMethodName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PaymentMethodName
		{
			get
			{
				return this._PaymentMethodName;
			}
			set
			{
				if ((this._PaymentMethodName != value))
				{
					this.OnPaymentMethodNameChanging(value);
					this.SendPropertyChanging();
					this._PaymentMethodName = value;
					this.SendPropertyChanged("PaymentMethodName");
					this.OnPaymentMethodNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PaymentMethod_Sale", Storage="_Sale", ThisKey="PaymentMethodID", OtherKey="PaymentMethodSale")]
		public EntitySet<Sale> Sale
		{
			get
			{
				return this._Sale;
			}
			set
			{
				this._Sale.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sale(Sale entity)
		{
			this.SendPropertyChanging();
			entity.PaymentMethod = this;
		}
		
		private void detach_Sale(Sale entity)
		{
			this.SendPropertyChanging();
			entity.PaymentMethod = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OperationProduct")]
	public partial class OperationProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OperationID;
		
		private int _SaleProduct;
		
		private int _ProductID;
		
		private decimal _ProductPrice;
		
		private decimal _ProductDiscount;
		
		private EntityRef<Sale> _Sale;
		
		private EntityRef<Products> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOperationIDChanging(int value);
    partial void OnOperationIDChanged();
    partial void OnSaleProductChanging(int value);
    partial void OnSaleProductChanged();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnProductPriceChanging(decimal value);
    partial void OnProductPriceChanged();
    partial void OnProductDiscountChanging(decimal value);
    partial void OnProductDiscountChanged();
    #endregion
		
		public OperationProduct()
		{
			this._Sale = default(EntityRef<Sale>);
			this._Products = default(EntityRef<Products>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OperationID
		{
			get
			{
				return this._OperationID;
			}
			set
			{
				if ((this._OperationID != value))
				{
					this.OnOperationIDChanging(value);
					this.SendPropertyChanging();
					this._OperationID = value;
					this.SendPropertyChanged("OperationID");
					this.OnOperationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleProduct", DbType="Int NOT NULL")]
		public int SaleProduct
		{
			get
			{
				return this._SaleProduct;
			}
			set
			{
				if ((this._SaleProduct != value))
				{
					if (this._Sale.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSaleProductChanging(value);
					this.SendPropertyChanging();
					this._SaleProduct = value;
					this.SendPropertyChanged("SaleProduct");
					this.OnSaleProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="Int NOT NULL")]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					if (this._Products.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductPrice", DbType="Decimal(18,2) NOT NULL")]
		public decimal ProductPrice
		{
			get
			{
				return this._ProductPrice;
			}
			set
			{
				if ((this._ProductPrice != value))
				{
					this.OnProductPriceChanging(value);
					this.SendPropertyChanging();
					this._ProductPrice = value;
					this.SendPropertyChanged("ProductPrice");
					this.OnProductPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDiscount", DbType="Decimal(18,2) NOT NULL")]
		public decimal ProductDiscount
		{
			get
			{
				return this._ProductDiscount;
			}
			set
			{
				if ((this._ProductDiscount != value))
				{
					this.OnProductDiscountChanging(value);
					this.SendPropertyChanging();
					this._ProductDiscount = value;
					this.SendPropertyChanged("ProductDiscount");
					this.OnProductDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sale_OperationProduct", Storage="_Sale", ThisKey="SaleProduct", OtherKey="SaleID", IsForeignKey=true)]
		public Sale Sale
		{
			get
			{
				return this._Sale.Entity;
			}
			set
			{
				Sale previousValue = this._Sale.Entity;
				if (((previousValue != value) 
							|| (this._Sale.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sale.Entity = null;
						previousValue.OperationProduct.Remove(this);
					}
					this._Sale.Entity = value;
					if ((value != null))
					{
						value.OperationProduct.Add(this);
						this._SaleProduct = value.SaleID;
					}
					else
					{
						this._SaleProduct = default(int);
					}
					this.SendPropertyChanged("Sale");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Products_OperationProduct", Storage="_Products", ThisKey="ProductID", OtherKey="ProductID", IsForeignKey=true)]
		public Products Products
		{
			get
			{
				return this._Products.Entity;
			}
			set
			{
				Products previousValue = this._Products.Entity;
				if (((previousValue != value) 
							|| (this._Products.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Products.Entity = null;
						previousValue.OperationProduct.Remove(this);
					}
					this._Products.Entity = value;
					if ((value != null))
					{
						value.OperationProduct.Add(this);
						this._ProductID = value.ProductID;
					}
					else
					{
						this._ProductID = default(int);
					}
					this.SendPropertyChanged("Products");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customers")]
	public partial class Customers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerID;
		
		private string _CustomerName;
		
		private string _CustomerSurname;
		
		private string _CustomerAddress;
		
		private string _CustomerTelephone;
		
		private string _CustomerOccupotion;
		
		private string _CustomerDetails;
		
		private System.Nullable<System.DateTime> _CustomerRegistrationDate;
		
		private System.Nullable<bool> _isActive;
		
		private System.Nullable<int> _CustomerReference;
		
		private decimal _CustomerAccount;
		
		private EntitySet<Sale> _Sale;
		
		private EntitySet<CustomerProcces> _CustomerProcces;
		
		private EntityRef<RefCustomer> _RefCustomer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnCustomerSurnameChanging(string value);
    partial void OnCustomerSurnameChanged();
    partial void OnCustomerAddressChanging(string value);
    partial void OnCustomerAddressChanged();
    partial void OnCustomerTelephoneChanging(string value);
    partial void OnCustomerTelephoneChanged();
    partial void OnCustomerOccupotionChanging(string value);
    partial void OnCustomerOccupotionChanged();
    partial void OnCustomerDetailsChanging(string value);
    partial void OnCustomerDetailsChanged();
    partial void OnCustomerRegistrationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCustomerRegistrationDateChanged();
    partial void OnisActiveChanging(System.Nullable<bool> value);
    partial void OnisActiveChanged();
    partial void OnCustomerReferenceChanging(System.Nullable<int> value);
    partial void OnCustomerReferenceChanged();
    partial void OnCustomerAccountChanging(decimal value);
    partial void OnCustomerAccountChanged();
    #endregion
		
		public Customers()
		{
			this._Sale = new EntitySet<Sale>(new Action<Sale>(this.attach_Sale), new Action<Sale>(this.detach_Sale));
			this._CustomerProcces = new EntitySet<CustomerProcces>(new Action<CustomerProcces>(this.attach_CustomerProcces), new Action<CustomerProcces>(this.detach_CustomerProcces));
			this._RefCustomer = default(EntityRef<RefCustomer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this.OnCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerName = value;
					this.SendPropertyChanged("CustomerName");
					this.OnCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerSurname", DbType="NVarChar(50)")]
		public string CustomerSurname
		{
			get
			{
				return this._CustomerSurname;
			}
			set
			{
				if ((this._CustomerSurname != value))
				{
					this.OnCustomerSurnameChanging(value);
					this.SendPropertyChanging();
					this._CustomerSurname = value;
					this.SendPropertyChanged("CustomerSurname");
					this.OnCustomerSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerAddress", DbType="NVarChar(400)")]
		public string CustomerAddress
		{
			get
			{
				return this._CustomerAddress;
			}
			set
			{
				if ((this._CustomerAddress != value))
				{
					this.OnCustomerAddressChanging(value);
					this.SendPropertyChanging();
					this._CustomerAddress = value;
					this.SendPropertyChanged("CustomerAddress");
					this.OnCustomerAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerTelephone", DbType="NVarChar(15)")]
		public string CustomerTelephone
		{
			get
			{
				return this._CustomerTelephone;
			}
			set
			{
				if ((this._CustomerTelephone != value))
				{
					this.OnCustomerTelephoneChanging(value);
					this.SendPropertyChanging();
					this._CustomerTelephone = value;
					this.SendPropertyChanged("CustomerTelephone");
					this.OnCustomerTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerOccupotion", DbType="NVarChar(150)")]
		public string CustomerOccupotion
		{
			get
			{
				return this._CustomerOccupotion;
			}
			set
			{
				if ((this._CustomerOccupotion != value))
				{
					this.OnCustomerOccupotionChanging(value);
					this.SendPropertyChanging();
					this._CustomerOccupotion = value;
					this.SendPropertyChanged("CustomerOccupotion");
					this.OnCustomerOccupotionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerDetails", DbType="NVarChar(400)")]
		public string CustomerDetails
		{
			get
			{
				return this._CustomerDetails;
			}
			set
			{
				if ((this._CustomerDetails != value))
				{
					this.OnCustomerDetailsChanging(value);
					this.SendPropertyChanging();
					this._CustomerDetails = value;
					this.SendPropertyChanged("CustomerDetails");
					this.OnCustomerDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerRegistrationDate", DbType="Date")]
		public System.Nullable<System.DateTime> CustomerRegistrationDate
		{
			get
			{
				return this._CustomerRegistrationDate;
			}
			set
			{
				if ((this._CustomerRegistrationDate != value))
				{
					this.OnCustomerRegistrationDateChanging(value);
					this.SendPropertyChanging();
					this._CustomerRegistrationDate = value;
					this.SendPropertyChanged("CustomerRegistrationDate");
					this.OnCustomerRegistrationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit")]
		public System.Nullable<bool> isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerReference", DbType="Int")]
		public System.Nullable<int> CustomerReference
		{
			get
			{
				return this._CustomerReference;
			}
			set
			{
				if ((this._CustomerReference != value))
				{
					if (this._RefCustomer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerReferenceChanging(value);
					this.SendPropertyChanging();
					this._CustomerReference = value;
					this.SendPropertyChanged("CustomerReference");
					this.OnCustomerReferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerAccount", DbType="Decimal(18,2) NOT NULL")]
		public decimal CustomerAccount
		{
			get
			{
				return this._CustomerAccount;
			}
			set
			{
				if ((this._CustomerAccount != value))
				{
					this.OnCustomerAccountChanging(value);
					this.SendPropertyChanging();
					this._CustomerAccount = value;
					this.SendPropertyChanged("CustomerAccount");
					this.OnCustomerAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customers_Sale", Storage="_Sale", ThisKey="CustomerID", OtherKey="CustomerID")]
		public EntitySet<Sale> Sale
		{
			get
			{
				return this._Sale;
			}
			set
			{
				this._Sale.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customers_CustomerProcces", Storage="_CustomerProcces", ThisKey="CustomerID", OtherKey="CustomerID")]
		public EntitySet<CustomerProcces> CustomerProcces
		{
			get
			{
				return this._CustomerProcces;
			}
			set
			{
				this._CustomerProcces.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RefCustomer_Customers", Storage="_RefCustomer", ThisKey="CustomerReference", OtherKey="RefCustomerID", IsForeignKey=true)]
		public RefCustomer RefCustomer
		{
			get
			{
				return this._RefCustomer.Entity;
			}
			set
			{
				RefCustomer previousValue = this._RefCustomer.Entity;
				if (((previousValue != value) 
							|| (this._RefCustomer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RefCustomer.Entity = null;
						previousValue.Customers.Remove(this);
					}
					this._RefCustomer.Entity = value;
					if ((value != null))
					{
						value.Customers.Add(this);
						this._CustomerReference = value.RefCustomerID;
					}
					else
					{
						this._CustomerReference = default(Nullable<int>);
					}
					this.SendPropertyChanged("RefCustomer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sale(Sale entity)
		{
			this.SendPropertyChanging();
			entity.Customers = this;
		}
		
		private void detach_Sale(Sale entity)
		{
			this.SendPropertyChanging();
			entity.Customers = null;
		}
		
		private void attach_CustomerProcces(CustomerProcces entity)
		{
			this.SendPropertyChanging();
			entity.Customers = this;
		}
		
		private void detach_CustomerProcces(CustomerProcces entity)
		{
			this.SendPropertyChanging();
			entity.Customers = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerProcces")]
	public partial class CustomerProcces : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerProccesID;
		
		private int _CustomerID;
		
		private int _ProccesType;
		
		private decimal _ProccesPrice;
		
		private System.DateTime _ProccesDate;
		
		private EntityRef<Customers> _Customers;
		
		private EntityRef<ProccesList> _ProccesList;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerProccesIDChanging(int value);
    partial void OnCustomerProccesIDChanged();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnProccesTypeChanging(int value);
    partial void OnProccesTypeChanged();
    partial void OnProccesPriceChanging(decimal value);
    partial void OnProccesPriceChanged();
    partial void OnProccesDateChanging(System.DateTime value);
    partial void OnProccesDateChanged();
    #endregion
		
		public CustomerProcces()
		{
			this._Customers = default(EntityRef<Customers>);
			this._ProccesList = default(EntityRef<ProccesList>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerProccesID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CustomerProccesID
		{
			get
			{
				return this._CustomerProccesID;
			}
			set
			{
				if ((this._CustomerProccesID != value))
				{
					this.OnCustomerProccesIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerProccesID = value;
					this.SendPropertyChanged("CustomerProccesID");
					this.OnCustomerProccesIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					if (this._Customers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProccesType", DbType="Int NOT NULL")]
		public int ProccesType
		{
			get
			{
				return this._ProccesType;
			}
			set
			{
				if ((this._ProccesType != value))
				{
					if (this._ProccesList.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProccesTypeChanging(value);
					this.SendPropertyChanging();
					this._ProccesType = value;
					this.SendPropertyChanged("ProccesType");
					this.OnProccesTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProccesPrice", DbType="Decimal(18,2) NOT NULL")]
		public decimal ProccesPrice
		{
			get
			{
				return this._ProccesPrice;
			}
			set
			{
				if ((this._ProccesPrice != value))
				{
					this.OnProccesPriceChanging(value);
					this.SendPropertyChanging();
					this._ProccesPrice = value;
					this.SendPropertyChanged("ProccesPrice");
					this.OnProccesPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProccesDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime ProccesDate
		{
			get
			{
				return this._ProccesDate;
			}
			set
			{
				if ((this._ProccesDate != value))
				{
					this.OnProccesDateChanging(value);
					this.SendPropertyChanging();
					this._ProccesDate = value;
					this.SendPropertyChanged("ProccesDate");
					this.OnProccesDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customers_CustomerProcces", Storage="_Customers", ThisKey="CustomerID", OtherKey="CustomerID", IsForeignKey=true)]
		public Customers Customers
		{
			get
			{
				return this._Customers.Entity;
			}
			set
			{
				Customers previousValue = this._Customers.Entity;
				if (((previousValue != value) 
							|| (this._Customers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customers.Entity = null;
						previousValue.CustomerProcces.Remove(this);
					}
					this._Customers.Entity = value;
					if ((value != null))
					{
						value.CustomerProcces.Add(this);
						this._CustomerID = value.CustomerID;
					}
					else
					{
						this._CustomerID = default(int);
					}
					this.SendPropertyChanged("Customers");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProccesList_CustomerProcces", Storage="_ProccesList", ThisKey="ProccesType", OtherKey="ProccesID", IsForeignKey=true)]
		public ProccesList ProccesList
		{
			get
			{
				return this._ProccesList.Entity;
			}
			set
			{
				ProccesList previousValue = this._ProccesList.Entity;
				if (((previousValue != value) 
							|| (this._ProccesList.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProccesList.Entity = null;
						previousValue.CustomerProcces.Remove(this);
					}
					this._ProccesList.Entity = value;
					if ((value != null))
					{
						value.CustomerProcces.Add(this);
						this._ProccesType = value.ProccesID;
					}
					else
					{
						this._ProccesType = default(int);
					}
					this.SendPropertyChanged("ProccesList");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categories")]
	public partial class Categories : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoryID;
		
		private string _CategoryName;
		
		private EntitySet<Products> _Products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoryIDChanging(int value);
    partial void OnCategoryIDChanged();
    partial void OnCategoryNameChanging(string value);
    partial void OnCategoryNameChanged();
    #endregion
		
		public Categories()
		{
			this._Products = new EntitySet<Products>(new Action<Products>(this.attach_Products), new Action<Products>(this.detach_Products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this.OnCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._CategoryID = value;
					this.SendPropertyChanged("CategoryID");
					this.OnCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(150)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this.OnCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._CategoryName = value;
					this.SendPropertyChanged("CategoryName");
					this.OnCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categories_Products", Storage="_Products", ThisKey="CategoryID", OtherKey="ProductCategorie")]
		public EntitySet<Products> Products
		{
			get
			{
				return this._Products;
			}
			set
			{
				this._Products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Products(Products entity)
		{
			this.SendPropertyChanging();
			entity.Categories = this;
		}
		
		private void detach_Products(Products entity)
		{
			this.SendPropertyChanging();
			entity.Categories = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Products : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductID;
		
		private string _ProductBarcode;
		
		private string _ProductName;
		
		private System.Nullable<int> _ProductCategorie;
		
		private System.Nullable<decimal> _ProductSalePrice;
		
		private string _ProductDescription;
		
		private System.Nullable<bool> _isActive;
		
		private System.Nullable<long> _ProductPiece;
		
		private EntitySet<Stock> _Stock;
		
		private EntitySet<OperationProduct> _OperationProduct;
		
		private EntityRef<Categories> _Categories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnProductBarcodeChanging(string value);
    partial void OnProductBarcodeChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnProductCategorieChanging(System.Nullable<int> value);
    partial void OnProductCategorieChanged();
    partial void OnProductSalePriceChanging(System.Nullable<decimal> value);
    partial void OnProductSalePriceChanged();
    partial void OnProductDescriptionChanging(string value);
    partial void OnProductDescriptionChanged();
    partial void OnisActiveChanging(System.Nullable<bool> value);
    partial void OnisActiveChanged();
    partial void OnProductPieceChanging(System.Nullable<long> value);
    partial void OnProductPieceChanged();
    #endregion
		
		public Products()
		{
			this._Stock = new EntitySet<Stock>(new Action<Stock>(this.attach_Stock), new Action<Stock>(this.detach_Stock));
			this._OperationProduct = new EntitySet<OperationProduct>(new Action<OperationProduct>(this.attach_OperationProduct), new Action<OperationProduct>(this.detach_OperationProduct));
			this._Categories = default(EntityRef<Categories>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductBarcode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductBarcode
		{
			get
			{
				return this._ProductBarcode;
			}
			set
			{
				if ((this._ProductBarcode != value))
				{
					this.OnProductBarcodeChanging(value);
					this.SendPropertyChanging();
					this._ProductBarcode = value;
					this.SendPropertyChanged("ProductBarcode");
					this.OnProductBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(150)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCategorie", DbType="Int")]
		public System.Nullable<int> ProductCategorie
		{
			get
			{
				return this._ProductCategorie;
			}
			set
			{
				if ((this._ProductCategorie != value))
				{
					if (this._Categories.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductCategorieChanging(value);
					this.SendPropertyChanging();
					this._ProductCategorie = value;
					this.SendPropertyChanged("ProductCategorie");
					this.OnProductCategorieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSalePrice", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ProductSalePrice
		{
			get
			{
				return this._ProductSalePrice;
			}
			set
			{
				if ((this._ProductSalePrice != value))
				{
					this.OnProductSalePriceChanging(value);
					this.SendPropertyChanging();
					this._ProductSalePrice = value;
					this.SendPropertyChanged("ProductSalePrice");
					this.OnProductSalePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDescription", DbType="NVarChar(400)")]
		public string ProductDescription
		{
			get
			{
				return this._ProductDescription;
			}
			set
			{
				if ((this._ProductDescription != value))
				{
					this.OnProductDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ProductDescription = value;
					this.SendPropertyChanged("ProductDescription");
					this.OnProductDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit")]
		public System.Nullable<bool> isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductPiece", DbType="BigInt")]
		public System.Nullable<long> ProductPiece
		{
			get
			{
				return this._ProductPiece;
			}
			set
			{
				if ((this._ProductPiece != value))
				{
					this.OnProductPieceChanging(value);
					this.SendPropertyChanging();
					this._ProductPiece = value;
					this.SendPropertyChanged("ProductPiece");
					this.OnProductPieceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Products_Stock", Storage="_Stock", ThisKey="ProductID", OtherKey="ProductID")]
		public EntitySet<Stock> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				this._Stock.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Products_OperationProduct", Storage="_OperationProduct", ThisKey="ProductID", OtherKey="ProductID")]
		public EntitySet<OperationProduct> OperationProduct
		{
			get
			{
				return this._OperationProduct;
			}
			set
			{
				this._OperationProduct.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Categories_Products", Storage="_Categories", ThisKey="ProductCategorie", OtherKey="CategoryID", IsForeignKey=true)]
		public Categories Categories
		{
			get
			{
				return this._Categories.Entity;
			}
			set
			{
				Categories previousValue = this._Categories.Entity;
				if (((previousValue != value) 
							|| (this._Categories.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categories.Entity = null;
						previousValue.Products.Remove(this);
					}
					this._Categories.Entity = value;
					if ((value != null))
					{
						value.Products.Add(this);
						this._ProductCategorie = value.CategoryID;
					}
					else
					{
						this._ProductCategorie = default(Nullable<int>);
					}
					this.SendPropertyChanged("Categories");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Stock(Stock entity)
		{
			this.SendPropertyChanging();
			entity.Products = this;
		}
		
		private void detach_Stock(Stock entity)
		{
			this.SendPropertyChanging();
			entity.Products = null;
		}
		
		private void attach_OperationProduct(OperationProduct entity)
		{
			this.SendPropertyChanging();
			entity.Products = this;
		}
		
		private void detach_OperationProduct(OperationProduct entity)
		{
			this.SendPropertyChanging();
			entity.Products = null;
		}
	}
}
#pragma warning restore 1591
